# src/cwm/git_cmd.py
import click
import pyperclip
import re
import os
import platform
from pathlib import Path
from .git_utils import (
    detect_project_type,
    generate_ssh_key,
    get_gitignore_content, 
    update_ssh_config, 
    get_configured_accounts,
    run_git_command,
    get_git_remote_url,
    get_current_branch,
    has_commits,
    SSH_CONFIG
)

# Simple defaults for gitignore to prevent "add all" disasters
DEFAULT_GITIGNORE = """
# Generated by CWM
node_modules/
venv/
.env
.DS_Store
__pycache__/
dist/
build/
.idea/
.vscode/
*.log
"""

@click.group("git")
def git_cmd():
    """Manage GitHub accounts and SSH keys."""
    pass

@git_cmd.command("add")
def add_account():
    # ... (Keep existing add_account logic exactly as it was) ...
    click.echo("--- CWM Git Account Wizard ---")
    alias = click.prompt("Enter a unique alias (e.g. 'work', 'personal')")
    alias = re.sub(r'[^a-z0-9_]', '', alias.lower())
    if not alias:
        click.echo("Invalid alias.")
        return
    email = click.prompt("Enter the email for this account")
    click.echo(f"Generating SSH key for '{alias}'...")
    try:
        key_path = generate_ssh_key(alias, email)
        update_ssh_config(alias, key_path)
        pub_key_path = key_path.with_suffix(".pub")
        if pub_key_path.exists():
            pub_key = pub_key_path.read_text().strip()
            click.echo(click.style("\nSUCCESS: SSH Key created and Config updated.", fg="green"))
            click.echo(f"Key: {key_path}")
            click.echo("-" * 60)
            click.echo(pub_key)
            click.echo("-" * 60)
            if click.confirm("Copy public key to clipboard?", default=True):
                pyperclip.copy(pub_key)
                click.echo("Copied! Go to GitHub -> Settings -> SSH Keys and add it.")
        else:
             click.echo("Error: Public key file not found.")
    except Exception as e:
        click.echo(f"Error: {e}", err=True)

@git_cmd.command("list")
def list_accounts():
    # ... (Keep existing list_accounts logic) ...
    accounts = get_configured_accounts()
    if not accounts:
        click.echo("No CWM-managed accounts found in ~/.ssh/config")
        return
    click.echo(f"Config File: {SSH_CONFIG}")
    click.echo("Configured Accounts:")
    for i, acc in enumerate(accounts):
        click.echo(f"  [{i+1}] {acc['alias']}")
        click.echo(f"      Host: {acc['host']}")
        click.echo(f"      Key:  {acc['key']}")
        click.echo("")

@git_cmd.command("setup")
def setup_repo():
    """Configure current folder with a Git account."""
    # 1. Select Account
    accounts = get_configured_accounts()
    if not accounts:
        click.echo("No accounts found. Run 'cwm git add' first.")
        return
        
    click.echo("Select account to use for this repo:")
    for i, acc in enumerate(accounts):
        click.echo(f"  [{i+1}] {acc['alias']} ({acc['host']})")
        
    try:
        choice = click.prompt("Enter number", type=int)
        if choice < 1 or choice > len(accounts):
            click.echo("Invalid selection.")
            return
    except:
        return
        
    selected = accounts[choice - 1]
    alias = selected['alias']
    ssh_host = selected['host'] 
    
    # 2. Init Repo Logic
    if not (Path.cwd() / ".git").exists():
        if click.confirm("Initialize new Git repository here?", default=True):
            run_git_command(["init"])
            run_git_command(["branch", "-M", "main"])
            click.echo("Initialized Git repository (branch set to 'main').")
    
    # 3. Configure User & Line Endings
    click.echo(f"\nConfiguring local user for '{alias}'...")
    name = click.prompt(f"Enter User Name for '{alias}'")
    email = click.prompt(f"Enter Email for '{alias}'")
    run_git_command(["config", "user.name", name])
    run_git_command(["config", "user.email", email])
    
    # --- NEW: Auto-CRLF Configuration ---
    # Windows handles line endings differently (\r\n) than Linux/Mac (\n).
    # Setting this prevents the annoying warnings.
    system = platform.system()
    crlf_setting = "true" if system == "Windows" else "input"
    run_git_command(["config", "core.autocrlf", crlf_setting])
    click.echo(f"Configured core.autocrlf = {crlf_setting} (for {system}).")

    click.echo("Local git config updated.")
    
    # 4. Configure Remote
    click.echo("\n--- Remote Setup ---")
    click.echo("Go to GitHub, create a repo, and copy the SSH URL.")
    raw_url = click.prompt("Paste URL")
    
    if "git@github.com:" in raw_url:
        new_url = raw_url.replace("git@github.com:", f"git@{ssh_host}:")
        click.echo(f"Rewriting URL to use alias: {new_url}")
    else:
        click.echo("Warning: URL format not standard. Using as-is.")
        new_url = raw_url
        
    current_remote = get_git_remote_url()
    
    if current_remote:
        click.echo(f"Current remote 'origin': {current_remote}")
        if click.confirm(f"Replace with new URL?"):
            run_git_command(["remote", "set-url", "origin", new_url])
            click.echo("Remote updated.")
    else:
        run_git_command(["remote", "add", "origin", new_url])
        click.echo("Remote 'origin' added.")
    
    # 5. Finalize and Automated Push
    current_branch = get_current_branch()
    has_data = has_commits()
    
    click.echo(click.style(f"\nSetup Complete! Repo linked to '{alias}'.", fg="green"))
    
    if has_data:
        # Existing repo with commits
        push_cmd = f"git push -u origin {current_branch}"
        click.echo(f"Repository is ready.")
        
        if click.confirm(f"Push to remote now? ({push_cmd})", default=True):
            click.echo("Pushing...")
            if run_git_command(["push", "-u", "origin", current_branch]):
                click.echo(click.style("Success! Pushed to remote.", fg="green"))
            else:
                click.echo(click.style("Push failed. Check your internet or SSH key.", fg="red"))
                pyperclip.copy(push_cmd)
                click.echo("Command copied to clipboard instead.")
    else:
        # Empty repo - Needs initial commit logic
        click.echo(click.style("Notice: You have no commits yet.", fg="yellow"))
        
        # --- NEW: Gitignore Check ---
        if not (Path.cwd() / ".gitignore").exists():
            # 1. Detect Type
            detected_type = detect_project_type(Path.cwd())
            
            # 2. Ask User with Default
            click.echo(f"Detected project type: {click.style(detected_type, bold=True)}")
            
            if click.confirm(f"Create .gitignore for {detected_type}?", default=True):
                # 3. Get Content and Write
                content = get_gitignore_content(detected_type)
                (Path.cwd() / ".gitignore").write_text(content)
                click.echo(f"Created .gitignore ({detected_type}).")
            else:
                # Optional: Let them choose manually if detection was wrong?
                # For now, we just skip to keep it fast.
                click.echo("Skipped .gitignore creation.")

        # Ask to Automate (The rest is same as before)
        if click.confirm("Do you want to Add, Commit, and Push automatically?", default=True):
            msg = click.prompt("Enter commit message", default="Initial commit")
            
            click.echo("1. Adding files...")
            run_git_command(["add", "."])
            
            click.echo(f"2. Committing ('{msg}')...")
            if run_git_command(["commit", "-m", msg]):
                click.echo("3. Pushing to remote...")
                if run_git_command(["push", "-u", "origin", current_branch]):
                    click.echo(click.style("Success! Your project is live on GitHub.", fg="green"))
                else:
                    click.echo(click.style("Push failed. Check permissions.", fg="red"))
                    click.echo(f"Run manually: git push -u origin {current_branch}")
            else:
                click.echo("Commit failed (maybe nothing to commit?).")
        
        else:
            # Fallback: Copy commands
            cmds = [
                "git add .",
                f'git commit -m "Initial commit"',
                f"git push -u origin {current_branch}"
            ]
            cmd_block = "\n".join(cmds)
            
            if click.confirm("Copy setup commands to clipboard?", default=True):
                pyperclip.copy(cmd_block)
                click.echo("Copied!")
            else:
                click.echo("Run these manually:")
                for c in cmds:
                    click.echo(f"  {c}")